# Generated by Django 5.2.4 on 2025-08-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_payment_payment_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_link",
            field=models.URLField(
                blank=True, max_length=512, null=True, verbose_name="Ссылка на оплату"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="session_id",
            field=models.CharField(
                blank=True, max_length=512, null=True, verbose_name="ID сессии"
            ),
        ),
    ]
